## INTRODUCTION 

---


##### USE CASES 
    OF BTG IT Sessions 2026 - Módulo 13: Inteligência Artificial


#####  ML APPROACH:  REGRESSION 
    - Predicts a numeric value
    - Utilizado quando se deseja prever um valor numérico
    - Geralmente consiste em encontrar uma relação entre um conjunto de dados de entrada e uma saída numérica.
    - Valores são contínuos

##### METRIC : Mean Squared Error (MSE)
    - O Erro Médio Quadrático (EMQ) — ou Mean Squared Error (MSE), em inglês — é uma métrica que serve para medir a qualidade de um modelo de previsão ou estimação (como regressões lineares, IA e modelos estatísticos). Ele calcula a média dos quadrados dos erros, ou seja, a diferença entre o valor real e o valor que o modelo previu.


##### APLICAÇÃO REAL (PROBLEMA REAL):
    Predição de preços de imóveis de um dataset público de Boston.

-------------------------------------------------------------------------------------

##### SCIKIT-LEARN WEBSITE

[https://scikit-learn.org/stable/](https://scikit-learn.org/stable/)

--------------------------------------------------------------------------------------------------------

## IMPLEMENTATION

 ---

In [23]:
# Installing required libraries

import numpy as np
from pydataset import data

# from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.model_selection import KFold

In [24]:
# Get the Boston dataset from the pydataset library
dataset = data('Boston')

In [25]:
# Verifying the first few rows of the dataset
dataset.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [26]:
dataset.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [27]:
# Removing outliers from the target variable 'medv'
dataset = dataset[~(dataset['medv'] >= 50.0)]  

prices = dataset['medv']
features = dataset.drop('medv', axis=1)

info = "The dataset has been successfully loaded and preprocessed. \nThe target variable 'medv' has been cleaned of outliers,\nand the features have been separated for further analysis."

print("$"*80)
print(f"\n{info}\n")
print("$"*80)

print("\n")
print("Features shape (lines, columns) :  ", features.shape)
print("Prices shape (lines, columns):   ", prices.shape)  

# print("BOSTON HOUSING DATASET HAS {} DATA POINTS WITH {} VARIABLES EACH.".format(dataset.shape[0], dataset.shape[1]))

print("BOSTON HOUSING DATASET HAS < {} > DATA POINTS WITH < {} > VARIABLES EACH.".format(*dataset.shape))

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

The dataset has been successfully loaded and preprocessed.
The target variable 'medv' has been cleaned of outliers,
and the features have been separated for further analysis.

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


Features shape (lines, columns) :   (490, 13)
Prices shape (lines, columns):    (490,)
BOSTON HOUSING DATASET HAS < 490 > DATA POINTS WITH < 14 > VARIABLES EACH.

In [28]:
# Get the minimum and maximum prices from the dataset

minimum_price = np.amin(prices)

maximum_price = np.amax(prices)

mean_price = np.mean(prices)

median_price = np.median(prices)

std_price = np.std(prices)

#  Show the calculated statistics for the target variable 'medv'

print("\n")
print("Statistics for Boston housing dataset over the target variable 'medv':")
print("\n")

print("Minimum price: ${:,.2f}".format(minimum_price))
print("Maximum price: ${:,.2f}".format(maximum_price))
print("Mean price: ${:,.2f}".format(mean_price))
print("Median price ${:,.2f}".format(median_price))
print("Standard deviation of prices: ${:,.2f}".format(std_price))

Statistics for Boston housing dataset over the target variable 'medv':


Minimum price: $5.00
Maximum price: $48.80
Mean price: $21.64
Median price $20.90
Standard deviation of prices: $7.86

In [29]:
prices

1      24.0
2      21.6
3      34.7
4      33.4
5      36.2
       ...
502    22.4
503    20.6
504    23.9
505    22.0
506    11.9
Name: medv, Length: 490, dtype: float64

In [30]:
features

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [31]:
#  Selecting the variables to be used for the regression model, based on their correlation with the target variable 'medv'

selected_variables1 = [
    "INDUS", "NOX", "RM", "AGE", "DIS", "TAX", "PTRATIO", "LSTAT"
]

selected_variables2 = [
    "CRIM", "ZN", "INDUS", "CHAS", "RAD", "BLACK", "LSTAT", "TAX"
]

# create a random selection to choose between the two sets of selected variables for the regression model
#  [1, 3[ mean generates a random integer between 1 and 2 (inclusive of 1, exclusive of 3)]
ran = np.random.randint(1, 3)

match ran:
    case 1:
        print("\n")
        print("Selected set 1 of variables for regression model: \n\n", selected_variables1)
        print("\n")
        
        features = dataset[[v.lower() for v in selected_variables1]]
    case 2:
        print("\n")
        print("Selected set 2 of variables for regression model: \n\n", selected_variables2)
        print("\n")
        features = dataset[[v.lower() for v in selected_variables2]]

Selected set 1 of variables for regression model:

 ['INDUS', 'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'LSTAT']

In [32]:
features.head(5)

   indus    nox     rm   age     dis  tax  ptratio  lstat
1   2.31  0.538  6.575  65.2  4.0900  296     15.3   4.98
2   7.07  0.469  6.421  78.9  4.9671  242     17.8   9.14
3   7.07  0.469  7.185  61.1  4.9671  242     17.8   4.03
4   2.18  0.458  6.998  45.8  6.0622  222     18.7   2.94
5   2.18  0.458  7.147  54.2  6.0622  222     18.7   5.33

In [33]:
features.head(5)

   indus    nox     rm   age     dis  tax  ptratio  lstat
1   2.31  0.538  6.575  65.2  4.0900  296     15.3   4.98
2   7.07  0.469  6.421  78.9  4.9671  242     17.8   9.14
3   7.07  0.469  7.185  61.1  4.9671  242     17.8   4.03
4   2.18  0.458  6.998  45.8  6.0622  222     18.7   2.94
5   2.18  0.458  7.147  54.2  6.0622  222     18.7   5.33

##### TRAIN AND TEST MODEL LinearRegrassion

In [34]:
# Preparing the model for training and testing
#  MODEL: Linear Regression, with 10-fold cross-validation and Min-Max scaling of features

# ---------------------------------------------------------------


l_regression = linear_model.LinearRegression()

# Definindo o número de folds para validação cruzada
kf = KFold(n_splits=10)

# Normalizing the features using Min-Max scaling, which scales the features to a range between 0 and 1. This is important for many machine learning algorithms that are sensitive to the scale of input data.
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(features)

# min_max_scaler2 = preprocessing.MinMaxScaler()
# x_scaled2 = min_max_scaler2.fit_transform(features_two)


print("\n")
print(f"X_scaled : \n, {x_scaled[1]}")
# print("\n")
# print(f"X_scaled2 : \n, {x_scaled2[1]}")
# print("\n")

X_scaled :
, [0.23444444 0.17283951 0.5479977  0.78269825 0.34852359 0.10496183
 0.55319149 0.19894415]

##### CROSS VALIDATION AND RESULTS OF ML MODEL LinearRegression

In [35]:
from sklearn.model_selection import cross_val_score

lr_scores = cross_val_score(l_regression, x_scaled, prices, cv=kf, scoring='neg_mean_absolute_error')

print("="*80)
print("RESULTS FOR LINEAR REGRESSION MODEL  (negative mean absolute error) ")
print("="*80)

print("\n")

print(f" ::>> ALL Cross-validation scores: {lr_scores}")
print(" ::>> MSE: {:.2f}".format(lr_scores.mean()))
print(" ::>> Standard deviation:  {:.2f}".format(lr_scores.std()))

================================================================================
RESULTS FOR LINEAR REGRESSION MODEL  (negative mean absolute error)
================================================================================


 ::>> ALL Cross-validation scores: [-2.3561457  -2.86836298 -2.44498229 -3.21768916 -3.25104662 -3.72462288
 -2.72694268 -6.78737053 -4.31266926 -3.13415602]
 ::>> MSE: -3.48
 ::>> Standard deviation:  1.23

##### TRAIN AND TEST MODEL RandomForestClassifier

In [36]:
# Preparing the model for training and testing
# MODEL: Random Forest Regressor, which is an ensemble learning method that operates by constructing multiple decision trees during training and outputting the mean prediction of the individual trees. It is used for regression tasks and can handle both numerical and categorical data.

# -----------------------------------------------------------------------------

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

regressor_rf = RandomForestRegressor(n_estimators=100, random_state=0) 

# Definindo o número de folds para validação cruzada
# kf = KFold(n_splits=10)

# Training the model using cross-validation and calculating the MSE scores
rf_scores = cross_val_score(regressor_rf, x_scaled, prices, cv=kf, scoring='neg_mean_absolute_error')
 

print("="*80)
print("RESULTS FOR RANDOM FOREST REGRESSOR MODEL  (negative mean absolute error) ")
print("="*80)

print(f" ::>> ALL Cross-validation scores: {rf_scores}")
print(f" ::>> MSE: {round(rf_scores.mean(), 2)}")
print(f" ::>> Standard deviation: {round(rf_scores.std(), 2)}")

================================================================================
RESULTS FOR RANDOM FOREST REGRESSOR MODEL  (negative mean absolute error)
================================================================================
 ::>> ALL Cross-validation scores: [-2.71422449 -1.39126531 -1.70487755 -3.38112245 -2.64381633 -3.04255102
 -2.13863265 -3.59414286 -4.04081633 -2.89820408]
 ::>> MSE: -2.75
 ::>> Standard deviation: 0.79

##### TRAIN AND TEST MODEL GradientBoostingClassifier

In [37]:
# Preparing the model for training and testing
# MODEL: Gradient Boosting Regressor, which is an ensemble learning method that builds a predictive model in a stage-wise fashion. It is used for regression tasks and can handle both numerical and categorical data. It combines the predictions of several base estimators to improve robustness over a single estimator.

# -----------------------------------------------------------------------

from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(n_estimators=100)

# Training the model using cross-validation and calculating the accuracy scores
gbr_scores = cross_val_score(gbr, x_scaled, prices, cv=kf, scoring='neg_mean_absolute_error')

# -----------------------------------------------------------------------
# results of the Gradient Boosting Regressor will be displayed below
# -----------------------------------------------------------------------

print("="*80)
print("RESULTS FOR GRADIENT BOOSTING REGRESSOR MODEL  (negative mean absolute error) ")
print("="*80)

print(f" ::>> ALL Cross-validation scores: \n{gbr_scores}")
print(" ::>> MSE:  %.2f" % gbr_scores.mean())
print(" ::>> Standard deviation: %.2f" % gbr_scores.std())

================================================================================
RESULTS FOR GRADIENT BOOSTING REGRESSOR MODEL  (negative mean absolute error)
================================================================================
 ::>> ALL Cross-validation scores:
[-2.61254251 -1.6653334  -2.83154714 -3.35039024 -2.6503705  -3.1928407
 -2.15412778 -3.5885915  -3.63115424 -3.21676887]
 ::>> MSE:  -2.89
 ::>> Standard deviation: 0.60

#####  GridSearchCV TECHNIQUE

In [38]:
# Preparing the model for training and testing
# MODEL: GridSearchCV, which is a technique for hyperparameter tuning that performs an exhaustive search over a specified parameter grid. It is used to find the best combination of hyperparameters for a given model by evaluating its performance using cross-validation.

# ----------------------------------------------------------------


from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, make_scorer

parameters = {
    'alpha': [0.9, 0.85],
    'learning_rate': [0.01, 0.05, 0.01],
    'max_depth': [2, 3],
    'min_samples_leaf': [5, 3],
    'min_samples_split': [2, 3],
    'n_estimators': [100, 80, 120]
}
gscv =  GridSearchCV(
    estimator=GradientBoostingRegressor(), 
    scoring=make_scorer(mean_squared_error, greater_is_better=False),
    param_grid=parameters, cv=10, n_jobs=-1
)

gscv.fit(x_scaled, prices)

# -----------------------------------------------------------------------
# Results of the GridSearchCV will be displayed below
# -----------------------------------------------------------------------

print("="*85)
print("RESULTS FOR GRIDSEARCHCV (negative mean squared error) across all searched params")
print("="*85)

print(f"::>> The best ESTIMATOR : \n{gscv.best_estimator_}")
print("::>> The best SCORE IS: %.2f" % gscv.best_score_)
print(f"::>> The best PARAMETERS : \n{gscv.best_params_}")

=====================================================================================
RESULTS FOR GRIDSEARCHCV (negative mean squared error) across all searched params
=====================================================================================
::>> The best ESTIMATOR :
GradientBoostingRegressor(learning_rate=0.05, max_depth=2, min_samples_leaf=5,
                          min_samples_split=3, n_estimators=120)
::>> The best SCORE IS: -12.34
::>> The best PARAMETERS :
{'alpha': 0.9, 'learning_rate': 0.05, 'max_depth': 2, 'min_samples_leaf': 5, 'min_samples_split': 3, 'n_estimators': 120}

#### TRAIN AND TEST GradientBoostingRegressor with GridSearchCV Techmique results

In [39]:
# APLICAR OS MELHORES VALORES PARA os parâmetros dO MODELO DE REGRESSÃO GRADIENT BOOSTING REGRESSOR, COM OS MELHORES PARÂMETROS ENCONTRADOS PELO GRIDSEARCHCV, PARA TREINAR E TESTAR O MODELO COM OS DADOS DE TREINAMENTO E TESTE.

gscv_bp = gscv.best_params_

# gscvbp
# list(gscv_best_params.items())

gbr = GradientBoostingRegressor(
    alpha = gscv_bp['alpha'],
    learning_rate =  gscv_bp['learning_rate'],
    max_depth = gscv_bp['max_depth'],
    min_samples_leaf = gscv_bp['min_samples_leaf'],
    min_samples_split = gscv_bp['min_samples_split'],
    n_estimators = gscv_bp['n_estimators'],
    random_state=30
)
# Training the model using cross-validation and calculating the accuracy scores
gbr_gscv_scores = cross_val_score(gbr, x_scaled, prices, cv=kf, scoring='neg_mean_absolute_error')

# -----------------------------------------------------------------------
# results of the Gradient Boosting Regressor will be displayed below
# -----------------------------------------------------------------------

print("="*80)
print("RESULTS FOR GRADIENT BOOSTING REGRESSOR MODEL V2 (negative mean absolute error) ")
print("="*80)

print(f" ::>> ALL Cross-validation scores: \n{gbr_gscv_scores}")
print(" ::>> MSE:  %.2f" % gbr_gscv_scores.mean())
print(" ::>> Standard deviation: %.2f" % gbr_gscv_scores.std())

================================================================================
RESULTS FOR GRADIENT BOOSTING REGRESSOR MODEL V2 (negative mean absolute error)
================================================================================
 ::>> ALL Cross-validation scores:
[-2.28552947 -1.53837721 -1.82131013 -2.9355383  -2.98446205 -3.0668024
 -2.21051625 -3.52776766 -3.32778144 -2.71608873]
 ::>> MSE:  -2.64
 ::>> Standard deviation: 0.62

#### Consolidation of Results

In [40]:
# Consolidação de resultados de todos os modelos testados acima, mostrando os melhores resultados de cada modelo.

# 1 - linear regression model
# 2 - random forest regressor model
# 3 - gradient boosting regressor model
# 4 - gradient boosting regressor model with best parmas estimated by gridsearchcv 

# -----------------------------------------------------------

print("="*80)
print("CONSOLIDATED RESULTS OF ALL MODELS TESTED")
print("="*80)

print("\n")

print("LinearRegressor model\n")
print(" ::>> MSE:  %.2f" % lr_scores.mean())
print(" ::>> Standard deviation: %.2f" % lr_scores.std())
print("-"*80)
print("RandomForestRegressor model\n")
print(" ::>> MSE:  %.2f" % rf_scores.mean())
print(" ::>> Standard deviation: %.2f" % rf_scores.std())
print("-"*80)
print("GradientBoostingRegressor model\n")
print(" ::>> MSE:  %.2f" % gbr_scores.mean())
print(" ::>> Standard deviation: %.2f" % gbr_scores.std())
print("-"*80)
print("GradientBoostingRegressor model with GridSearchCV best params\n")
print(" ::>> MSE:  %.2f" % gbr_gscv_scores.mean())
print(" ::>> Standard deviation: %.2f" % gbr_gscv_scores.std())
print("\n")
print("$"*80)

================================================================================
CONSOLIDATED RESULTS OF ALL MODELS TESTED
================================================================================


LinearRegressor model

 ::>> MSE:  -3.48
 ::>> Standard deviation: 1.23
--------------------------------------------------------------------------------
RandomForestRegressor model

 ::>> MSE:  -2.75
 ::>> Standard deviation: 0.79
--------------------------------------------------------------------------------
GradientBoostingRegressor model

 ::>> MSE:  -2.89
 ::>> Standard deviation: 0.60
--------------------------------------------------------------------------------
GradientBoostingRegressor model with GridSearchCV best params

 ::>> MSE:  -2.64
 ::>> Standard deviation: 0.62


$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

## CONCLUSION

Com base nos treinamentos, testes e análises dos resultados dos 3 algorítmos de aprendizado máquina:
- Linear Regressor
- Random Forest Regressor
- Gradient Boosting Regressor
- Gradient Boosting Regressor com parâmetros otimizados pelo GridSearchCV

Chegou-se a uma resposta: 

Deve-se escolher o modelo  `Gradient Boosting Regressor` otimizado pelo GridSearchCV por MOTIVOS listados abaixo:

1 - Menor erro médio quadrático em valores absolutos

2 - Menor Desvio padrão