## INTRODUCTION 

---


##### USE CASES 
    OF BTG IT Sessions 2026 - Módulo 13: Inteligência Artificial


#####  ML APPROACH:  REGRESSION 
    - Predicts a numeric value
    - Utilizado quando se deseja prever um valor numérico
    - Geralmente consiste em encontrar uma relação entre um conjunto de dados de entrada e uma saída numérica.
    - Valores são contínuos

##### METRIC : Mean Squared Error (MSE)
    - O Erro Médio Quadrático (EMQ) — ou Mean Squared Error (MSE), em inglês — é uma métrica que serve para medir a qualidade de um modelo de previsão ou estimação (como regressões lineares, IA e modelos estatísticos). Ele calcula a média dos quadrados dos erros, ou seja, a diferença entre o valor real e o valor que o modelo previu.


##### APLICAÇÃO REAL (PROBLEMA REAL):
    Predição de preços de imóveis de um dataset público de Boston.

-------------------------------------------------------------------------------------

##### SCIKIT-LEARN WEBSITE

[https://scikit-learn.org/stable/](https://scikit-learn.org/stable/)

--------------------------------------------------------------------------------------------------------

## IMPLEMENTATION

In [1]:
# Installing required libraries

import pandas as pd
import numpy as np
from pydataset import data

# from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [2]:
# Get the Boston dataset from the pydataset library
dataset = data('Boston')

In [3]:
# Verifying the first few rows of the dataset
dataset.head(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
6,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
7,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
8,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
9,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
10,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [4]:
dataset.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [5]:
# Removing outliers from the target variable 'medv'
dataset = dataset[~(dataset['medv'] >= 50.0)]  

prices = dataset['medv']
features = dataset.drop('medv', axis=1)

info = "The dataset has been successfully loaded and preprocessed. \nThe target variable 'medv' has been cleaned of outliers,\nand the features have been separated for further analysis."

print("$"*80)
print(f"\n{info}\n")
print("$"*80)

print("\n")
print("Features shape (lines, columns) :  ", features.shape)
print("Prices shape (lines, columns):   ", prices.shape)  

# print("BOSTON HOUSING DATASET HAS {} DATA POINTS WITH {} VARIABLES EACH.".format(dataset.shape[0], dataset.shape[1]))

print("BOSTON HOUSING DATASET HAS < {} > DATA POINTS WITH < {} > VARIABLES EACH.".format(*dataset.shape))

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

The dataset has been successfully loaded and preprocessed.
The target variable 'medv' has been cleaned of outliers,
and the features have been separated for further analysis.

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


Features shape (lines, columns) :   (490, 13)
Prices shape (lines, columns):    (490,)
BOSTON HOUSING DATASET HAS < 490 > DATA POINTS WITH < 14 > VARIABLES EACH.

In [6]:
# Get the minimum and maximum prices from the dataset

minimum_price = np.amin(prices)

maximum_price = np.amax(prices)

mean_price = np.mean(prices)

median_price = np.median(prices)

std_price = np.std(prices)

#  Show the calculated statistics for the target variable 'medv'

print("\n")
print("Statistics for Boston housing dataset over the target variable 'medv':")
print("\n")

print("Minimum price: ${:,.2f}".format(minimum_price))
print("Maximum price: ${:,.2f}".format(maximum_price))
print("Mean price: ${:,.2f}".format(mean_price))
print("Median price ${:,.2f}".format(median_price))
print("Standard deviation of prices: ${:,.2f}".format(std_price))

Statistics for Boston housing dataset over the target variable 'medv':


Minimum price: $5.00
Maximum price: $48.80
Mean price: $21.64
Median price $20.90
Standard deviation of prices: $7.86

In [13]:
prices

1      24.0
2      21.6
3      34.7
4      33.4
5      36.2
       ...
502    22.4
503    20.6
504    23.9
505    22.0
506    11.9
Name: medv, Length: 490, dtype: float64

In [7]:
features

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [ ]:
#  Selecting the variables to be used for the regression model, based on their correlation with the target variable 'medv'

selected_variables1 = [
    "INDUS", "NOX", "RM", "AGE", "DIS", "TAX", "PTRATIO", "LSTAT"
]

selected_variables2 = [
    "CRIM", "ZN", "INDUS", "CHAS", "RAD", "BLACK", "LSTAT"
]

features_one = features[[v.lower() for v in selected_variables1]]

features_two = features[[v.lower() for v in selected_variables2]]

In [9]:
features_one.head(10)

    indus    nox     rm    age     dis  tax  ptratio  lstat
1    2.31  0.538  6.575   65.2  4.0900  296     15.3   4.98
2    7.07  0.469  6.421   78.9  4.9671  242     17.8   9.14
3    7.07  0.469  7.185   61.1  4.9671  242     17.8   4.03
4    2.18  0.458  6.998   45.8  6.0622  222     18.7   2.94
5    2.18  0.458  7.147   54.2  6.0622  222     18.7   5.33
6    2.18  0.458  6.430   58.7  6.0622  222     18.7   5.21
7    7.87  0.524  6.012   66.6  5.5605  311     15.2  12.43
8    7.87  0.524  6.172   96.1  5.9505  311     15.2  19.15
9    7.87  0.524  5.631  100.0  6.0821  311     15.2  29.93
10   7.87  0.524  6.004   85.9  6.5921  311     15.2  17.10

In [10]:
features_two.head(10)

       crim    zn  indus  chas  rad   black  lstat
1   0.00632  18.0   2.31     0    1  396.90   4.98
2   0.02731   0.0   7.07     0    2  396.90   9.14
3   0.02729   0.0   7.07     0    2  392.83   4.03
4   0.03237   0.0   2.18     0    3  394.63   2.94
5   0.06905   0.0   2.18     0    3  396.90   5.33
6   0.02985   0.0   2.18     0    3  394.12   5.21
7   0.08829  12.5   7.87     0    5  395.60  12.43
8   0.14455  12.5   7.87     0    5  396.90  19.15
9   0.21124  12.5   7.87     0    5  386.63  29.93
10  0.17004  12.5   7.87     0    5  386.71  17.10

##### TRAIN AND TEST MODEL LinearRegrassion

In [14]:
''' Preparing the model for training and testing
 MODEL: logistic regression, which is a statistical method for analyzing datasets in which there are one or more independent variables that determine an outcome. The outcome is measured with a dichotomous variable (in which there are only two possible outcomes).
'''

l_regression = linear_model.LinearRegression()

# Definindo o número de folds para validação cruzada
kf = KFold(n_splits=10)

# Normalizing the features using Min-Max scaling, which scales the features to a range between 0 and 1. This is important for many machine learning algorithms that are sensitive to the scale of input data.
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(features_one)

min_max_scaler2 = preprocessing.MinMaxScaler()
x_scaled2 = min_max_scaler2.fit_transform(features_two)


print("\n")
print(f"X_scaled : \n, {x_scaled[1]}")
print("\n")
print(f"X_scaled2 : \n, {x_scaled2[1]}")
print("\n")

X_scaled :
, [0.23444444 0.17283951 0.5479977  0.78269825 0.34852359 0.10496183
 0.55319149 0.19894415]


X_scaled2 :
, [2.35922539e-04 0.00000000e+00 2.34444444e-01 0.00000000e+00
 4.34782609e-02 1.00000000e+00 1.98944151e-01]

In [18]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(l_regression, x_scaled, prices, cv=kf, scoring='neg_mean_absolute_error')

print("\n")
print(f"Cross-validation scores (negative mean absolute error) for the first set of features: \n\n {scores}")

print("\n")
print(f"Mean of cross-validation scores (MSE): \n  {scores.mean()}")
print(f"\nStandard deviation of cross-validation scores: \n {scores.std()}")

Cross-validation scores (negative mean absolute error) for the first set of features:

 [-2.3561457  -2.86836298 -2.44498229 -3.21768916 -3.25104662 -3.72462288
 -2.72694268 -6.78737053 -4.31266926 -3.13415602]


Mean of cross-validation scores (MSE):
  -3.4823988127829937

Standard deviation of cross-validation scores:
 1.2332137157202945

##### RESULT OF ML MODEL LogisticRegression

In [ ]:
# Show the accuracy scores for each fold in a more readable format

# Mean accuracy of the model across all folds
print("Mean accuracy: {:.3f}".format(scores.mean()))

# Accuracy scores for each fold
print("Accuracy scores for each fold: \n ", scores)

# Standard deviation of the accuracy scores 
print("Standard deviation of accuracy scores: ", round((scores.std() * 2), 3))  # multiplied by 2 for a 95% confidence interval

##### VIEW CONFUSION MATRIX FOR LogisticRegression Model

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
import matplotlib.pyplot as plt

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

lr.fit(x_train, y_train)
y_predict = lr.predict(x_test)

conf_matrix = confusion_matrix(y_test, y_predict)

disp = ConfusionMatrixDisplay(
    confusion_matrix=conf_matrix, display_labels=lr.classes_)


disp.plot(cmap='viridis')
plt.show()

##### TRAIN AND TEST MODEL RandomForestClassifier

In [ ]:
# Preparing the model for training and testing
# MODEL: Randomforest 

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier() 

# Definindo o número de folds para validação cruzada
kf = KFold(n_splits=10)

# Training the model using cross-validation and calculating the accuracy scores
rf_scores = cross_val_score(rf, X, Y, cv=kf, scoring='accuracy')

##### RESULT OF MODEL  RandomForestClassifier

In [ ]:
# Show the accuracy scores for each fold in a more readable format

# Mean accuracy of the model across all folds
print("RandomForest Mean accuracy: {:.3f}".format(rf_scores.mean()))

# Accuracy scores for each fold
# print("Accuracy scores for each fold: \n ", rf_scores)

# Standard deviation of the accuracy scores 
print("RandomForest Standard deviation of accuracy scores: ", round((rf_scores.std() * 2), 3))

##### VIEW CONFUSION MATRIX FOR RandomForestClassifier Model

In [ ]:

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

rf.fit(x_train, y_train)
y_predict = rf.predict(x_test)

conf_matrix = confusion_matrix(y_test, y_predict)

disp = ConfusionMatrixDisplay(
    confusion_matrix=conf_matrix, display_labels=rf.classes_)


disp.plot(cmap='Greens')
plt.show()

##### TRAIN AND TEST MODEL GradientBoostingClassifier

In [ ]:
# Preparing the model for training and testing
# MODEL: Gradient Boosting Classifier 

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier() 

# Definindo o número de folds para validação cruzada
kf = KFold(n_splits=10)

# Training the model using cross-validation and calculating the accuracy scores
gb_scores = cross_val_score(gb, X, Y, cv=kf, scoring='accuracy')


# -----------------------------------------------------------------------
# results of the Gradient Boosting Classifier will be displayed below
# -----------------------------------------------------------------------
print("GradientBoosting Mean accuracy: {:.3f}".format(gb_scores.mean()))

# Standard deviation of the accuracy scores 
print("GradientBoosting Standard deviation of accuracy scores: ", round((gb_scores.std() * 2), 3))

##### VIEW CONFUSION MATRIX FOR GradientBoostingClassifier Model

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

gb.fit(x_train, y_train)
y_predict = gb.predict(x_test)

conf_matrix = confusion_matrix(y_test, y_predict)

disp = ConfusionMatrixDisplay(
    confusion_matrix=conf_matrix, display_labels=gb.classes_)


disp.plot(cmap='Oranges')
plt.show()

### CONCLUSÃO DO PROBLEMA

Com base nos treinamentos, testes e análises dos resultados dos 3 algorítmos de aprendizado máquina:
- Logistic Regression
- Random Forest Classifier
- Gradient Boosting Classifier

Chegou-se a uma resposta: 

Deve-se escolher o modelo  `Gradient Boosting Classifier` por MOTIVOS listados abaixo:

1 - Alta taxa de acerto

2 - Maior acurácia entre todos os modelos

3 - Traria menor prejuízo para o banco